### ISSUE TITLE
Envy v4.1

### ISSUE THREAD

**Issue by RealPrankster2877** [Haaaqs/envy-client-issues#13]
I was trying to set the antibot to Mineplex mode.
I typed in setting antibot Mineplex in the console.
what pops up is 
Mode: [Hypixel, Mineplex]
The mode doesn't change at all.

Edit: I got banned from mineplex due to this.

**Comment by Haaaqs** [comment]
Sorry to hear you got banned but this has been fixed for next release. For now, just use the TabGUI to change the modes. Ability to change modes will be added to the ClickGUI soon.

**Comment by hfghwpgg** [comment]
yep, changing settings with console is broken for modes (like criticals or antibot)

**Comment by SmashAce12** [comment]
you have to type in "Setting antibot mode Mineplex"
