### ISSUE TITLE
ESP ISSUE

### ISSUE THREAD

**Issue by issuebug14** [Haaaqs/envy-client-issues#16]
When you enable ESP the screen goes black.

**Comment by Haaaqs** [comment]
Try turning off Fast render. Its a video option in settings.

**Comment by issuebug14** [comment]
It works now thank you for the fast reply :)

**Comment by Haaaqs** [comment]
Glad it's fixed, I recommend just using Nametags on its own instead of ESP.

**Comment by issuebug14** [comment]
I like nametags too but it dont render far do you know how I can make it longer or if I can't can you make a slider for the nametag render.
