### ISSUE TITLE
more issues ;p

### ISSUE THREAD

**Issue by hfghwpgg** [Haaaqs/envy-client-issues#3]
my last report was pretty bad so i decided to test more and i have results. aura isnt as bad as it was yesterday (maybe 3.6 update fixed some things) but still sometimes it dont hit enemy that im fighting with (maybe hitting bot?). especially after fighting with many players at once and then going "1v1". also i found that aura like to hit people behind me, even when i have player in front of me. old "infov" option will be enough to fix that (i think :P) also i'd love to see "switch" aura mode. and you cant modify module settings in console. glhf with testing and fixing :)

**Comment by Haaaqs** [comment]
I will take a look at the not hitting issue once again. As for hitting players behind you, I can add InFOV back. And for switch I most likely will not add that in, will just add one attack modes for the aura (closest, lowest hp, highest/lowest armor).

**Comment by Haaaqs** [comment]
Fixed that bug you are getting banned because some modules don't bypass. I am not 100% which ones don't bypass. You can try this config on Hypixel. 

**config load https://pastebin.com/raw/zXrxzhF3**

**Comment by Haaaqs** [comment]
Added InFOV to Aura. An update will be released later today.
