### ISSUE TITLE
Speed & Aura

### ISSUE THREAD

**Issue by BartekSTV** [Haaaqs/envy-client-issues#6]
Hi,
I would like to ask you to add a new speed mode, i.e. Bhop and slightly improved aura (CPS (increase and decrease, from 1.0 to 20.0))

Thank you
My English is Bad :D
sorry for mistakes

**Comment by BartekSTV** [comment]
Client Is Best of Best

**Comment by Haaaqs** [comment]
Added that changing ability you are talking about.

**Comment by BartekSTV** [comment]
okey, thank you very much


Get the Boomerang Email App <http://boomerangapp.com/mobile> on your phone



----------
On Wed, Jun 27, 2018 at 10:02 PM, iHaq <notifications@github.com> wrote:

Added that changing ability you are talking about.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Haaaqs/envy-client-issues/issues/6#issuecomment-400793766>,
or mute the thread
