### ISSUE TITLE
Killaura

### ISSUE THREAD

**Issue by SadSonic** [Haaaqs/envy-client-issues#9]
The client is good but the killaura sucks i try all settings dont work men fix that please stop fix in speed or fly FIX IN KILLAURA

**Comment by SadSonic** [comment]
I know it takes a while to do more ... is no excuse for killaura on a server with a shit anti cheat not working please stop saying this and will ask for help to improve this killaura please. The rest is great

**Comment by Haaaqs** [comment]
The aura has been tested to be working. You probably have something on that
causing it to not work. I recommend you delete the client and the Envy
folder and redownloading it.

**Comment by SadSonic** [comment]
I did but it does not continue to work. But I think I know why. And because killaura is iotimized for mineplex and hypixel but for other servers I'm not going to give an example goes on this server minigames.redesky.com tests killaura here see if it is not bugged if not tell me the settings you put

**Comment by SadSonic** [comment]
then tell me how it went xD

**Comment by Haaaqs** [comment]
The server is running AAC([Advanced Anticheat](https://www.spigotmc.org/resources/aac-advanced-anti-cheat-hack-kill-aura-blocker.6442/)). This client is not designed to work on AAC.

**Comment by Haaaqs** [comment]
[Advanced Anticheat](url)
